version: '3.7'
services:
  blockchain:
    image: chain
    build:
      context: .
    volumes:
      - .:/home/app
    command: python chain/blockchain/start.py
    depends_on:
      - chain-db
      - chain-redis
    environment:
      PYTHONUNBUFFERED: '1'
      POSTGRES_DB_HOST: 'chain-db'
      REDIS_HOST: 'chain-redis'
      CHAIN_CONFIG_FOLDER: 'ark/devnet/'

  chain-p2p:
    image: chain
    volumes:
      - .:/home/app
    command: python chain/p2p_service/start.py
    depends_on:
      - chain-db
      - chain-redis
    environment:
      PYTHONUNBUFFERED: '1'
      POSTGRES_DB_HOST: 'chain-db'
      REDIS_HOST: 'chain-redis'
      SERVER_HOST: '0.0.0.0'
      CHAIN_CONFIG_FOLDER: 'ark/devnet/'
    ports:
      - '4002:8080'

  chain-p2p-huey:
    image: chain
    volumes:
      - .:/home/app
    command: huey_consumer.py chain.hughie.main.huey -n -C -k greenlet -w 10
    depends_on:
      - chain-db
      - chain-redis
    environment:
      PYTHONUNBUFFERED: '1'
      POSTGRES_DB_HOST: 'chain-db'
      REDIS_HOST: 'chain-redis'
      CHAIN_CONFIG_FOLDER: 'ark/devnet/'

  chain-db:
    image: postgres:11.2
    volumes:
        - ark-db:/var/lib/postgresql/data

  chain-redis:
    image: redis:5.0.3

volumes:
  ark-db:
