version: 2
jobs:
  test:
    working_directory: ~/ark
    environment:
      IMAGE_NAME: chain
      CHAIN_CONFIG_FOLDER: tests/config/
    docker:
      - image: circleci/python:3.7.2-stretch
      - image: circleci/postgres:9.6.9
      - image: circleci/redis:5.0.3
    steps:
      - checkout
      - run:
          name: Install requirements
          command: sudo pip install -r requirements.txt
      - run:
          name: Run linting
          command: flake8 .
      - run:
          name: Run tests
          command: py.test -vv -s -x

workflows:
  version: 2
  build-master:
    jobs:
      - test:
          filters:
            branches:
              only: master
